host = "localhost:8080"
url = "http://localhost:8080"

salt = "wewsalt"

redis_prefix = "lainfile"

no_access_extensions = ["exe", "rar"]
no_upload_extensions = ["exe"]

xforwarded = true
xforwarded_index = 1
